# Generated by Django 5.2.5 on 2025-09-09 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_options_alter_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='contact_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docs', 'docx', 'txt'])]),
        ),
    ]
